### PR TITLE
Large overhaul of GLM codebase

### PR DESCRIPTION
**Pull request by berkgercek**
The GLM code base was getting very, very ugly. I had implemented a linear, rather than nonlinear, model but subclassed the non-linear model rather than a proper refactoring. 

This PR will basically change the entire API for the `brainbox.modeling` module. Shouldn't affect anything else.

In brief:

- Design matrix generation and fitting of neural data are performed by two separate classes, `design_matrix.DesignMatrix` and either `linear.LinearGLM` or `poisson.PoissonGLM`
- Both the linear model and poisson model above inherit a common class called `NeuralModel` which has most of the methods necessary for treating data
- Some utility functions have been moved to `brainbox.modeling.utils`, in particular a class called `SequentialSelector` which allows you to run stepwise regressor selection on the data. This used to be a nasty chunk of code in the GLM object but I rewrote from scratch and based it on `sklearn.feature_selection.SequentialFeatureSelector`, which doesn't support feature groups (which is what I need) or intermediate-model scoring.

I also removed the tests for the modeling submodule for now, because I need to give some serious thought as to what to put there versus in the integration tests for ibllib.

### CODE REVIEW

**Comment by k1o0** [comment]
I love these commit messages

**Comment by berkgercek** [comment]
I've been reading a lot of James Mickens' articles lately...

https://mickens.seas.harvard.edu/wisdom-james-mickens

Also I'm not sure why tests are failing now.

**Comment by k1o0** [comment]
You can ignore the Github status checks for now.  The Windows one has never passed and the Ubuntu one is redundant and unreliable.  As long as the UCL checks pass it's safe to merge.

**Comment by k1o0** [comment]
I just realized you opened the PR into master.  You have to merge into develop I'm afraid.  Mind re-opening onto the correct branch?

**Comment by berkgercek** [comment]
Oh yeah! sorry didn't realize I opened it into master. I'll do that now.

**Pull request closed without merging**
