### PR TITLE
Wrote a Brainbox function to map values on atlas

### PR DESCRIPTION
**Pull request by guidomeijer**
The new brainbox functions in brainbox.atlas allow the user to specify a list of allen atlas acronyms and a list of values (e.g. decoding performance), the plot_atlas function then generates slices through the allen atlas as specified coordinates and plots the values as color. This way you can visualize the result of any brain wide analysis you did.

### CODE REVIEW

**Comment by k1o0** [comment]
A couple of tests are failing:
```
======================================================================

FAIL: test_differentiate_units (brainbox.tests.test_task.TestTask)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/int-brain-lab/ibllib/brainbox/tests/test_task.py", line 67, in test_differentiate_units

    self.assertTrue(np.size(sig_units) == 1)

AssertionError: False is not true

======================================================================

FAIL: test_responsive_units (brainbox.tests.test_task.TestTask)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/int-brain-lab/ibllib/brainbox/tests/test_task.py", line 47, in test_responsive_units

    self.assertTrue(np.size(sig_units) == 125)

AssertionError: False is not true
```

Could you look into them?

**Comment by guidomeijer** [comment]
Because I'm calculating significance slightly different now I had to change the test to accommodate for this. All good now.

**Comment by k1o0** [comment]
Looks like you just need to flake `atlas.py` now

**Comment by guidomeijer** [comment]
The maximum line length is 99 right?

**Comment by k1o0** [comment]
> The maximum line length is 99 right?

Yes

**Comment by guidomeijer** [comment]
Ok, it should be good now

**Comment by guidomeijer** [comment]
As requested during the meeting I removed the relative and star imports

**Comment by nbonacchi** [comment]
OK not sure about the code but I fast-forwarded your branch to latest develop (it was 293 commits behind), tests pass locally, waiting on Travis.

**Comment by berkgercek** [comment]
I think some of the theorists want to use the atlas funcs as they're super handy. I fixed the flaking issues, so hopefully this should be ready to pull.

**Comment by nbonacchi** [comment]
@guidomeijer if you're done with this we can merge.
TODO (after merge) suggestion from the brain wide map task force: highlight only the left hemisphere to more accurately depict the location of the recorded activity

**Comment by guidomeijer** [comment]
Yes I'm done

**Pull request merged**
