### PR TITLE
Drift-Raster example plot

### PR DESCRIPTION
**Pull request by GaelleChapuis**
Added an example to one>ephys

### CODE REVIEW

**Comment by mayofaulkner** [comment]
provide the file or a way that the csv file is not hardcoded to a path

**Comment by nbonacchi** [comment]
Your PR should be to develop not master

**Comment by GaelleChapuis** [comment]
This example has been incorporated by @mayofaulkner already ( https://int-brain-lab.github.io/iblenv/notebooks_external/docs_compute_drift.html ) so you can delete this PR

**Comment by oliche** [comment]
I had to change the target branch to develop, +GaelleChapuis could you please handle merge conflicts and I'll merge this

**Comment by oliche** [comment]
Cherrypicked commits

**Pull request closed without merging**
